# Generated by Django 2.1 on 2018-08-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProprietarioVeiculo', to='core.Pessoa', verbose_name='Proprietário do veículo'),
            preserve_default=False,
        ),
    ]
