# Generated by Django 2.1 on 2018-08-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180823_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametros',
            old_name='atualizado_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='atualizado_at',
            new_name='atualizado_em',
        ),
    ]
