# Generated by Django 2.1 on 2018-08-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180823_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovRotativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(verbose_name='Data de entrada')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de saída')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor da hora')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago?')),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='core.Veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Movimento Rotativo',
                'verbose_name_plural': 'Movimentos Rotativo',
            },
        ),
    ]
