# Generated by Django 2.1 on 2018-08-24 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180824_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Início da Cobrança')),
                ('valor_mes', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor do mês')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_mensal', to='core.Veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Movimento Mensalista',
                'verbose_name_plural': 'Movimentos Mensalista',
            },
        ),
    ]
