# Generated by Django 2.1 on 2018-08-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180827_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProprietarioVeiculo', to='core.Pessoa', verbose_name='Proprietário do veículo'),
        ),
    ]
